# Generated by Django 4.1.13 on 2026-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstaffs',
            name='feedback_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='feedback_reply',
            field=models.TextField(blank=True, default=''),
        ),
    ]
