# Generated by Django 4.1.13 on 2026-04-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_alter_feedbackstaffs_feedback_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstaff',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Medical Leave', 'Medical Leave'), ('Emergency Leave', 'Emergency Leave'), ('Personal Leave', 'Personal Leave'), ('Other', 'Other')], default='Casual Leave', max_length=50),
        ),
        migrations.AddField(
            model_name='leavereportstudent',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Medical Leave', 'Medical Leave'), ('Emergency Leave', 'Emergency Leave'), ('Personal Leave', 'Personal Leave'), ('Other', 'Other')], default='Casual Leave', max_length=50),
        ),
    ]
