# Generated by Django 4.1.13 on 2026-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_leavereportstaff_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Medical Leave', 'Medical Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Casual Leave', 'Casual Leave'), ('Personal Leave', 'Personal Leave'), ('Family Emergency', 'Family Emergency'), ('Bereavement Leave', 'Bereavement Leave'), ('Emergency Leave', 'Emergency Leave'), ('Half Day', 'Half Day'), ('Work From Home', 'Work From Home'), ('Conference Leave', 'Conference Leave'), ('Training Leave', 'Training Leave'), ('Other', 'Other')], default='Casual Leave', max_length=50),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Medical Leave', 'Medical Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Casual Leave', 'Casual Leave'), ('Personal Leave', 'Personal Leave'), ('Family Emergency', 'Family Emergency'), ('Bereavement Leave', 'Bereavement Leave'), ('Exam Leave', 'Exam Leave'), ('Study Leave', 'Study Leave'), ('Sports Leave', 'Sports Leave'), ('Cultural Event', 'Cultural Event'), ('Emergency Leave', 'Emergency Leave'), ('Half Day', 'Half Day'), ('Work From Home', 'Work From Home'), ('Other', 'Other')], default='Casual Leave', max_length=50),
        ),
    ]
